/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        "danger": boolean;
        "type"?: 'primary' | 'dashed';
    }
    interface MyButtonGroup {
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyButtonGroupElement extends Components.MyButtonGroup, HTMLStencilElement {
    }
    var HTMLMyButtonGroupElement: {
        prototype: HTMLMyButtonGroupElement;
        new (): HTMLMyButtonGroupElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-button-group": HTMLMyButtonGroupElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "danger"?: boolean;
        "onClickButton"?: (event: CustomEvent<any>) => void;
        "type"?: 'primary' | 'dashed';
    }
    interface MyButtonGroup {
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-button-group": MyButtonGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-button-group": LocalJSX.MyButtonGroup & JSXBase.HTMLAttributes<HTMLMyButtonGroupElement>;
        }
    }
}
